// Real local HTTP + SQLite checks. Creates only task-specific QA records and removes them in finally.
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,unlink,readdir} from 'node:fs/promises';
import {parseEnv} from 'node:util';
import {randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import sharp from 'sharp';
import {PrismaClient} from '@prisma/client';
const env=parseEnv(await readFile('.env','utf8'));Object.assign(process.env,env);
const base=env.APP_ORIGIN!;const db=new PrismaClient();const checks:string[]=[];const idPrefix='qa-'+randomUUID();let cookie='';let qaId='';const originalSettings=await db.setting.findMany();const originalWorks=await db.work.findMany({orderBy:{id:'asc'}});const beforeUploads=new Set(await readdir('public/uploads'));
const qaMedia=new Set<string>();
const record=(name:string)=>{checks.push(name);console.log('PASS '+name);};
async function req(route:string,method='GET',data?:unknown,auth=true,origin=base){return fetch(base+route,{method,redirect:'manual',headers:{...(auth&&cookie?{Cookie:cookie}:{}),...(method!=='GET'?{Origin:origin}:{}),...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});}
try{
 for(const url of ['/','/works','/about',...originalWorks.map(w=>'/works/'+w.slug)])assert.equal((await req(url)).status,200);
 assert.equal((await req('/does-not-exist')).status,404);record('public routes and nine real details');
 assert.equal((await req('/api/admin/works','GET',undefined,false)).status,401);assert.equal((await req('/admin','GET',undefined,false)).status,307);assert.equal((await req('/api/admin/login','POST',{user:env.ADMIN_USER,password:'wrong'},false)).status,401);assert.equal((await req('/api/admin/login','POST',{user:env.ADMIN_USER,password:env.ADMIN_PASSWORD},false,'https://evil.invalid')).status,403);
 const login=await req('/api/admin/login','POST',{user:env.ADMIN_USER,password:env.ADMIN_PASSWORD},false);assert.equal(login.status,200);cookie=login.headers.get('set-cookie')!.split(';')[0];assert.match(login.headers.get('set-cookie')!,/HttpOnly/i);assert.match(login.headers.get('set-cookie')!,/Secure/i);assert.match(login.headers.get('set-cookie')!,/SameSite=Strict/i);record('authentication, origin check and secure session cookie');
 const image=await sharp({create:{width:1900,height:900,channels:3,background:'#bada55'}}).png().toBuffer();const form=new FormData();form.set('file',new File([new Uint8Array(image)],idPrefix+'.png',{type:'image/png'}));const upload=await fetch(base+'/api/admin/upload',{method:'POST',headers:{Cookie:cookie,Origin:base},body:form});assert.equal(upload.status,200);const media=(await upload.json()).path;qaMedia.add(path.basename(media));qaMedia.add(path.basename(media.replace('-1600','-800')));for(const [size,file] of [[1600,media],[800,media.replace('-1600','-800')]] as const){const r=await req(file);assert.equal(r.status,200);const meta=await sharp(Buffer.from(await r.arrayBuffer())).metadata();assert.equal(meta.width,size);assert.equal(meta.format,'webp');}record('live upload, WebP 800/1600 and post-build file serving');
 for(const [name,bytes] of [['bad.png',Buffer.from('not an image')],['bad.svg',Buffer.from('<svg/>')],['huge.png',Buffer.alloc(10*1024*1024+1)]] as const){const f=new FormData();f.set('file',new File([new Uint8Array(bytes)],name));const r=await fetch(base+'/api/admin/upload',{method:'POST',headers:{Cookie:cookie,Origin:base},body:f});assert.ok(r.status>=400);}
 assert.equal((await req('/uploads/%2e%2e%2f.env')).status,404);record('invalid, oversized and traversal upload cases');
 for(const ext of ['mp4','webm']){const bytes=await readFile('tests/fixtures/qa-video.'+ext);const f=new FormData();f.set('file',new File([new Uint8Array(bytes)],idPrefix+'.'+ext));const r=await fetch(base+'/api/admin/upload',{method:'POST',headers:{Cookie:cookie,Origin:base},body:f});assert.equal(r.status,200);const video=(await r.json()).path;qaMedia.add(path.basename(video));const partial=await fetch(base+video,{headers:{Range:'bytes=0-15'}});assert.equal(partial.status,206);assert.equal(partial.headers.get('content-range'),`bytes 0-15/${bytes.length}`);assert.deepEqual(Buffer.from(await partial.arrayBuffer()),bytes.subarray(0,16));const invalidRange=await fetch(base+video,{headers:{Range:`bytes=${bytes.length+10}-`}});assert.equal(invalidRange.status,416);}
 record('MP4 and WebM upload, immediate Range 206 and invalid Range 416');
 const sample={title:idPrefix,slug:idPrefix,cover:media,images:[media],imageCaptions:['QA 图说明'],summary:'QA 临时案例',description:[{type:'paragraph',text:'<script>alert(1)</script>'}],tags:['QA'],year:'2026',link:'',order:9999,published:false};const create=await req('/api/admin/works','POST',sample);assert.equal(create.status,201);qaId=(await create.json()).id;assert.equal((await req('/works/'+idPrefix)).status,404);assert.equal((await req('/api/admin/works','POST',sample)).status,409);assert.equal((await req('/api/admin/works/'+qaId,'PUT',{...sample,link:'javascript:alert(1)'})).status,400);record('draft exclusion, unique slug and invalid update rejection');
 assert.equal((await req('/api/admin/works/'+qaId,'PUT',{...sample,published:true})).status,200);const rendered=await (await req('/works/'+idPrefix)).text();assert.ok(rendered.includes('&lt;script&gt;'));assert.equal((await db.work.findUniqueOrThrow({where:{id:qaId}})).published,true);const query=await (await req('/api/admin/works?q='+idPrefix)).json();assert.equal(query.total,1);assert.equal(query.items[0].id,qaId);record('publishing, safe text rendering, search and persisted state');
 assert.equal((await req('/api/admin/works/'+qaId,'PUT',{...sample,published:false})).status,200);assert.equal((await req('/works/'+idPrefix)).status,404);record('unpublish immediate on public detail');
 const settings=Object.fromEntries(originalSettings.map(s=>[s.key,s.value]));assert.equal((await req('/api/admin/settings','PUT',{...settings,subtitle:idPrefix})).status,200);assert.ok((await (await req('/')).text()).includes(idPrefix));assert.equal((await db.setting.findUniqueOrThrow({where:{key:'subtitle'}})).value,idPrefix);record('settings update immediate and persisted');
 const first=originalWorks[0];await db.work.update({where:{id:first.id},data:{summary:'QA seed-preservation '+idPrefix}});execFileSync(process.execPath,['node_modules/tsx/dist/cli.mjs','prisma/seed.ts'],{env:process.env,stdio:'pipe'});assert.equal(await db.work.count(),originalWorks.length+1);assert.equal((await db.work.findUniqueOrThrow({where:{id:first.id}})).summary,'QA seed-preservation '+idPrefix);await db.work.update({where:{id:first.id},data:{summary:first.summary}});record('repeat seed preserves edits and produces no duplicate projects');
 assert.equal((await req('/api/admin/works/'+qaId,'DELETE')).status,200);assert.equal(await db.work.findUnique({where:{id:qaId}}),null);qaId='';record('delete confirmation API and record removal');
 await req('/api/admin/logout','POST');record('logout clears session cookie');
}finally{
 if(qaId)await db.work.deleteMany({where:{id:qaId,title:idPrefix}});
 for(const s of originalSettings){const current=await db.setting.findUnique({where:{key:s.key}});if(current?.value===idPrefix)await db.setting.update({where:{key:s.key},data:{value:s.value}});}
 for(const w of originalWorks){const current=await db.work.findUnique({where:{id:w.id}});if(current?.summary==='QA seed-preservation '+idPrefix)await db.work.update({where:{id:w.id},data:{summary:w.summary}});}
 for(const file of qaMedia)if(!beforeUploads.has(file))await unlink(path.resolve('public/uploads',file));
 await db.$disconnect();await mkdir('evidence',{recursive:true});await writeFile('evidence/runtime.json',JSON.stringify({time:new Date().toISOString(),checks,qaRecordsCleaned:true},null,2));
}
